blank_issues_enabled: false

contact_links:
  - name: 💥 FAQ
    url: https://github.com/vbti-development/onedl-mmdeploy/tree/main/docs/en/faq.md
    about: Check if your issue already has solutions
  - name: 💬 Forum
    url: https://github.com/vbti-development/onedl-mmdeploy/discussions
    about: Ask general usage questions and discuss with other MMDeploy community members
