name: backend-ort

on:
  pull_request:
    paths-ignore:
      - "demo/**"
      - "tools/**"
      - "docs/**"

env:
  PIP_PRE: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_ort:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install mmdeploy
        run: |
          python -m pip install torch==2.5.1 torchvision
          python -m pip install onedl-mmcv onedl-mim
          python tools/scripts/build_ubuntu_x64_ort.py 8
          python -c 'import mmdeploy.apis.onnxruntime as ort_api; assert ort_api.is_available(with_custom_ops=True)'
      - name: test mmpretrain full pipeline
        run: |
          python -m mim install onedl-mmpretrain
          export MMDEPLOY_DIR=$(pwd)
          export ONNXRUNTIME_DIR=$MMDEPLOY_DIR/../mmdeploy-dep/onnxruntime-linux-x64-1.8.1
          export LD_LIBRARY_PATH=$ONNXRUNTIME_DIR/lib:$MMDEPLOY_DIR/build/install/lib:$LD_LIBRARY_PATH
          bash .github/scripts/linux/test_full_pipeline.sh ort cpu
