name: backend-rknn

on:
  pull_request:
    paths-ignore:
      - "csrc/**"
      - "demo/csrc/**"
      - "CMakeLists.txt"
      - "docs/**"

env:
  PIP_PRE: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # build_rknpu2:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #       with:
  #         submodules: 'recursive'
  #     - name: update
  #       run: sudo apt update
  #     - name: cross compile
  #       run: |
  #         sh -xe tools/scripts/ubuntu_cross_build_rknn.sh rk3588
  build_rknpu:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: update
        run: sudo apt update
      - name: cross compile
        run: |
          sh -xe tools/scripts/ubuntu_cross_build_rknn.sh rv1126
